const router = require('express').Router()
const ownerRoutes = require('./owner')
const productsRoutes = require('./products')
const managerRoutes = require('./manager')
const warungRoutes = require('./warung')
const { authentication } = require('../middlewares/authentication')
const { authorize } = require('../middlewares/authorization')
const transactionRoute = require('./transaction')
const newsRoutes = require('./news')
const categoryRoutes = require('./category')
router.use('/owner', ownerRoutes)
router.use('/manager', managerRoutes)
router.use(authentication)
router.use('/products', productsRoutes)
router.use('/warung', warungRoutes)
router.use('/transaction', transactionRoute)
router.use('/news', newsRoutes)
router.use('/categories', categoryRoutes)
module.exports = router
